{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsf.javautils",
    "module": "java-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "76fcvgbuyjcopclpcyujjpemxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 8273,
          "sha512": "a57fd75f9df00c1f6588766bee2ab00849a19feab15f896985c68375b978de9306f5d90c17de7036c7b6627701ddbcd98780119f965d88edc5a63b54c903d2b8",
          "sha256": "a0f57556a709eebec7a807d6308439fe1ff66728b82b5ec55df87e219689d339",
          "sha1": "852c1db07b687b6312a386ebd9bdd4558b40f626",
          "md5": "143e7413b4c3d556448520836da28fc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 8273,
          "sha512": "a57fd75f9df00c1f6588766bee2ab00849a19feab15f896985c68375b978de9306f5d90c17de7036c7b6627701ddbcd98780119f965d88edc5a63b54c903d2b8",
          "sha256": "a0f57556a709eebec7a807d6308439fe1ff66728b82b5ec55df87e219689d339",
          "sha1": "852c1db07b687b6312a386ebd9bdd4558b40f626",
          "md5": "143e7413b4c3d556448520836da28fc7"
        }
      ]
    }
  ]
}
