{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsf.javautils",
    "module": "java-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ixulhvjwovfrjdnlh5jougxe6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 15422,
          "sha512": "57057192a43947375dc30d4aa8ecf68b2c997e0310fb230a57f4f863e44388257a8ee9f3e139dc1555e5262635f23d714c89d629e6497b1e3cdd4044761d9868",
          "sha256": "6f4ed5b9048a0ccce9364a93aec1ea28e1067b6a20f642eeb4ce6cae49bcf288",
          "sha1": "b3b9b98fd76f7d03bc12526fc135731f189dfe2d",
          "md5": "b1adf0c1a9a8e89373a0431e3e0ce389"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 15422,
          "sha512": "57057192a43947375dc30d4aa8ecf68b2c997e0310fb230a57f4f863e44388257a8ee9f3e139dc1555e5262635f23d714c89d629e6497b1e3cdd4044761d9868",
          "sha256": "6f4ed5b9048a0ccce9364a93aec1ea28e1067b6a20f642eeb4ce6cae49bcf288",
          "sha1": "b3b9b98fd76f7d03bc12526fc135731f189dfe2d",
          "md5": "b1adf0c1a9a8e89373a0431e3e0ce389"
        }
      ]
    }
  ]
}
